---

- name: Update the hostname (pt. 1) - hostname cmd
  hostname:
    name: "{{hostname_short}}"

- name: Update the hostname (pt. 2) - (/etc/hostname)
  copy:
    content: "{{hostname_short}}{{'\n'}}"
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644

- name: Update the hostname (pt. 3) - (/etc/hosts)
  lineinfile:
    dest: /etc/hosts
    regexp: item.regexp
    line: item.line
    state: present
  when:
    - { regexp: "^127.0.0.1", line: "127.0.0.1{{'\t'}}{{hostname}}{% if inventory_hostname != hostname_short %}{{'\t'}}{{hostname_short}}{% endif %}{{'\t'}}localhost" }
    - { regexp: "^::1", line: "::1{{'\t\t'}}{{hostname}}{% if inventory_hostname != hostname_short %}{{'\t'}}{{hostname_short}}{% endif %}{{'\t'}}localhost ip6-localhost ip6-loopback" }

