---

- name: Update the hostname - hostname cmd
  hostname:
    name: "{{hostname_short}}"

- name: Update the hostname - (/etc/hostname)
  copy:
    content: "{{hostname_short}}\n"
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644

- name: Update the hostname - (/etc/hosts)
  lineinfile:
    dest:   '/etc/hosts'
    regexp: '{{ item.regexp }}'
    line:   '{{ item.line }}'
    state:  '{{ item.state | default("present") }}'
  with_items:
    - "{{ hostname_hosts }}"
    - "{{ hostname_hosts_add }}"

