---

- name: Update the hostname (pt. 1) - hostname cmd
  hostname:
    name: "{{hostname_short}}"

- name: Update the hostname (pt. 2) - (/etc/hostname)
  copy:
    content: "{{hostname_short}}{{'\n'}}"
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644

- name: Update the hostname (pt. 3) - (/etc/hosts)
  lineinfile:
    dest: /etc/hosts
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - "{{ hostname_hosts }}"
    - "{{ hostname_hosts_add }}"

