# file: hostname/tasks/main.yml

- name: Hostname | Update the hostname (pt. 1) - hostname cmd
  hostname:
    name: "{{inventory_hostname_short}}"

- name: Hostname | Update the hostname (pt. 2) - (/etc/hostname)
  copy:
    content: "{{inventory_hostname_short}}"
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644

- name: Hostname | Update the hostname (pt. 3) - (/etc/hosts)
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ ansible_ssh_host}}"
    line: "{{ ansible_ssh_host}} {{'\t'}}{{inventory_hostname}}{% if inventory_hostname != inventory_hostname_short %}{{'\t'}}{{inventory_hostname_short}}{% endif %}"
    state: present
