---
- name: "Ensure dbus installed"
  apt:
    name: "{{anxs_hostname_packages}}"
    state: present
  tags: hostname
  when: ansible_os_family == "Debian"

- name: "Update the hostname (pt. 1) - hostname cmd"
  hostname:
    name: "{{inventory_hostname_short}}"

- name: Update the hostname (pt. 2) - (/etc/hostname)
  copy:
    content: "{{inventory_hostname_short}}{{'\n'}}"
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644

- name: "Update the IPv4 hostname (pt. 3) - (/etc/hosts)"
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.0.1"
    line: "127.0.0.1\t\t{{inventory_hostname}}{% if inventory_hostname != inventory_hostname_short %}\t{{inventory_hostname_short}}{% endif %}\tlocalhost"
    state: present
  when: ansible_virtualization_type != 'docker'

- name: "Update the IPv6 hostname (pt. 3) - (/etc/hosts)"
  lineinfile:
    dest: /etc/hosts
    regexp: "^::1"
    line: "::1\t\t{{inventory_hostname}}{% if inventory_hostname != inventory_hostname_short %}\t{{inventory_hostname_short}}{% endif %}\tlocalhost ip6-localhost ip6-loopback"
    state: present
  when: ansible_virtualization_type != 'docker'

- name: "Remove raspberrypi override if exists"
  lineinfile:
    dest: "/etc/hosts"
    regexp: "^127.0.1.1.+"
    state: absent

- name: "Install MDNS Components"
  apt:
    name: "{{anxs_hostname_mdns_packages}}"
    state: present
  when: 'ansible_os_family == "Debian" and hostname_avahi'
