# file: hostname/tasks/main.yml

- name: Hostname | Update the hostname (pt. 1) - hostname cmd
  hostname:
    name: "{{hostname_name}}"

- name: Hostname | Update the hostname (pt. 2) - (/etc/hostname)
  template:
    src: etc_hostname.j2
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644

- name: Hostname | Update the hostname (pt. 3) - (/etc/hosts)
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.0.1    {{ hostname_fqdn }}    {{ hostname_name }}"
    line: "127.0.0.1    {{ hostname_fqdn }}    {{ hostname_name }}"
    state: present
    backup: yes
    backrefs: yes
