---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: "anxs-hostname-${MOLECULE_OS:-ubuntu}-${MOLECULE_VERSION:-2404}"
    image: "${MOLECULE_IMAGE:-geerlingguy/docker-ubuntu2404-ansible:latest}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    command: ${MOLECULE_DOCKER_COMMAND:-""}

provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible-${USER}/tmp/
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/..:${HOME}/.ansible/roles"

verifier:
  name: testinfra

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
